#!/bin/bash

echo "═══════════════════════════════════════════════════════════════════"
echo "  UCL: AI Layer - Meta-Recursion at Every Level"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "The Ultimate Meta-Programming Achievement:"
echo "  🤖 AI that generates UCL"
echo "  📝 UCL that defines functions"
echo "  ⚙️  Functions that compute results"
echo ""
echo "Every layer is UCL. Every layer is traceable. Every layer is mockable."
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "Press Enter to see Mock AI generate factorial function..."
read

cargo run --quiet -- ai examples/ai_generate_factorial.json --verbose

echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "🎯 What Just Happened:"
echo ""
echo "1. Mock AI received instruction: 'Write a factorial function'"
echo "2. AI matched 'factorial' in its knowledge base"
echo "3. AI generated UCL code (DefineFunction with If/else and recursion)"
echo "4. The generated code is PURE UCL!"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "Press Enter to see the full chain (AI → Compile → Execute)..."
read

cargo run --quiet -- ai examples/ai_chain.json --verbose

echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "🌟 The Power of Mockable Abstractions:"
echo ""
echo "You can test ANY combination:"
echo "  ✓ Mock AI + Mock VM (fast, deterministic)"
echo "  ✓ Mock AI + Real VM (test execution)"
echo "  ✓ Real AI + Mock VM (test AI output)"
echo "  ✓ Real AI + Real VM (production)"
echo ""
echo "Every layer is:"
echo "  • Traceable - See exact input/output"
echo "  • Mockable - Swap real for mock"
echo "  • Testable - Assert at each step"
echo "  • Universal - Works across all substrates"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "🪆 Meta-Recursion:"
echo ""
echo "UCL can even generate UCL that generates UCL!"
echo ""
echo "  UCL(prompt to AI)"
echo "    → AI generates UCL(function definition)"
echo "      → Execute UCL(compute factorial)"
echo "        → Result: 120"
echo ""
echo "Infinite abstraction layers, all in UCL. 🤯"
echo ""
echo "See AI_LAYER.md for complete documentation."
echo "═══════════════════════════════════════════════════════════════════"

